apiVersion: v2
name: streamprocessing
description: Homework Stream Proccessing OTUS

type: application

version: 0.1.0
appVersion: v1

dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: rabbitmq
    version: 6.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled