apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "AllowedHosts": "*",
      "Services":
      {
        "Billing": "http://billing-service",
        "Orders": "http://orders-service"
      }
    }
  