#База данных заказов
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  ORDERSDB_URI: {{ printf "postgres://%s:%s@%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.ordersDbName  | b64enc | quote }}
  USERSDB_URI: {{ printf "postgres://%s:%s@%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.usersDbName  | b64enc | quote }}
  BILLINGDB_URI: {{ printf "postgres://%s:%s@%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.billingDbName  | b64enc | quote }}
  NOTIFYDB_URI: {{ printf "postgres://%s:%s@%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.notifyDbName  | b64enc | quote }}
---
#Брокер
apiVersion: v1
kind: Secret
metadata:
  name: rabbit-secret
type: Opaque
data:
  RabbitMQ_URI: {{ printf "amqp://%s:%s@%s:5672" .Values.rabbitmq.rabbitmq.username .Values.rabbitmq.rabbitmq.password (include "rabbitmq.fullname" .)  | b64enc | quote}}